
services:
  api:
    image: small-restapi:latest
    container_name: small-restapi
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: general
      DB_PASSWORD: 123
      DB_NAME: hr_saas_api
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: small-restapi-db
    environment:
      POSTGRES_USER: general
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hr_saas_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: